# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Edward Pieluc"
description:	       "Portfolio"
author:              "Edward Pieluc"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:vbnnbfbn
#  path: rss-feed.xml
